version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: memes
      POSTGRES_PASSWORD: memes
    ports:
      - 5432:5432
  memegrid:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 8080:8080
