version: 2

jobs:
  check:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

      - run:
          name: Run check
          command: ./gradlew check

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          destination: code-coverage
          path: build/reports/jacoco/test/html

      - store_artifacts:
          destination: test-results
          path: build/reports/tests/test

      - store_artifacts:
          destination: code-analysis
          path: build/reports/detekt

workflows:
  version: 2
  check:
    jobs:
      - check
