version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: memes
      POSTGRES_PASSWORD: memes
    ports:
      - 5432:5432
  memegrid:
    image: edvinas108/meme-grid:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: on-failure
    command: -u db:5432/memes -d https://memes.danevicius.lt -c
